### ISSUE TITLE
Prevent Deletion of a Case when there is a Related Behavior Involvement Record

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/EDA#912] opened 2019-09-09 23:42 UTC
- Request : Enhancement to Current Behavior

- Current Behavior : If a Case Record that has one or more Behavior Involvement records is deleted, the Behavior Involvement records become "orphaned" -- ie, the Behavior Involvement records have no associated Case record (which is a required field).

- Expected Behavior : Behavior Involvement Records should not become orphaned

- Acceptance Criteria : Given a Case record with one to many Behavior Involvement records; When I attempt to delete the Case record; I am not left with any orphaned Behavior Involvement records.

- Notes : 
-- "We can prevent the user from deleting the case if it has a Behavior Involvement. They could then delete the Behavior Involvement themselves and then delete the case (assuming that's an option). We could also warn them that if the case is deleted, we will also delete the related BI."
-- "Use TDTM to enforce so that customers can turn on/off those triggers." 

- Steps to Reproduce : 
1. Create a Case
2. From the Case Related List, create 2 Behavior Involvement Records
3. From the Case, click the "Delete" button
--> Actual Result : Case is deleted, and Behavior Involvement Records no longer have a Case assigned to them.
--> Expected Result : User is prevented from creating a Behavior Involvement record that does not have a Case assigned to it.

**Comment by dgamboni** [comment] 2019-09-09 23:59
**lurch: add

**Comment by LurchTheButler** [comment] 2019-09-10 00:00
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAX2QAO" target="_blank">W-035911</a>

**Comment by robertbwatson** [comment] 2020-02-11 18:42
Closing this issue as a dupe of #1091 -- fyi @dgamboni @skosgi1, we created a lot of these issues in the past and they're already linked to work items

**Closed by robertbwatson** 2020-02-11 18:42 UTC
Labels: accepted, enhancement

**Comment by skosgi1** [comment] 2020-02-11 18:46
Oops I didn't realize that. Thanks @robertbwatson
