### ISSUE TITLE
Namespaced org: Heda Settings Page: Some dropdowns aren't showing values

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/EDA#571] opened 2018-03-16 01:06 UTC
Created a namespaced org using meta ci. @weizsforg  also saw this when he did this cci command- 
cci org scratch dev_namespaced spaced

Go to Heda Settings- check all dropdowns to see where this is happening. I feel like I noticed it an another area.
But where I noticed it first was:
Heda Settings->system tab
The default account model was blank then when clicked on Edit button there were no available options.

![default account model blank](https://user-images.githubusercontent.com/35311289/37498422-ad92fa1e-2894-11e8-9724-e5ffae6965df.png)

some settings:
![namespace](https://user-images.githubusercontent.com/35311289/37498413-9c845ec0-2894-11e8-9925-4d201ed71a3f.png)

**Comment by annejackson** [comment] 2018-03-16 01:06
**lurch:add

**Comment by LurchTheButler** [comment] 2018-03-16 01:10
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000A2jVKAAZ" target="_blank">W-023352</a>

**Comment by ceiroa** [comment] 2018-03-16 14:56
@annejackson This might not be a bug. It might just be that the record types have not yet been assigned to your profile.

**Comment by jacebryan** [comment] 2019-01-10 18:58
@annejackson - were you able to confirm if the bug you reported was due to the record type access on your profile? If not please assign the Accepted label. Thank you!

**Comment by annejackson** [comment] 2019-01-10 19:24
@jacebryan  I know that when I have seen this problem in the past (in a sandbox or something) it was because I didn't have any account record types showing for my profile. I haven't checked with this in a namespaced scratch org in a while...but that could have been the issue.

**Comment by aligeez** [comment] 2019-10-07 16:11
This issue is no longer reproducible. Closing.

**Closed by aligeez** 2019-10-07 16:11 UTC
Labels: accepted, bug
