### ISSUE TITLE
[EDA] - [EDA] - Add Ability to Block deletion of Terms when Course Offerings Exist (Prevent Deletion of Course Offering if Term is Deleted)

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/EDA#1038] opened 2019-12-30 21:50 UTC
Background : With regard to deleting Terms if they have associated Course Offerings, if we delete a Term it will also delete the associated Course Offering. In some situations, users may want to Prevent deletion of Terms if there are associated Course Offerings via a Custom Setting

Do you want to request a *feature* or report a *bug*? - FEATURE

What is the current behavior? - IF THE USER DELETES A TERM, ALL THE ASSOCIATED COURSE OFFERINGS ARE ALSO DELETED

What is the expected behavior? - USER CAN ENABLE A SETTING THAT WILL PREVENT DELETION OF COURSE OFFERINGS WHEN TERM IS DELETED, AND ALSO DISPLAY AN ERROR MESSAGE

What is the motivation / use case for changing the behavior? - DATA INTEGRITY

Acceptance Criteria : 

  - **Given**: I try to delete a Term that has associated Course Offerings
  - **When**: The setting to prevent deletion of child records is enabled in Custom Hierarchy Settings
  - **Then**: I am prevented from deleting the Term and I see an error message. 

Steps to Reproduce : 
1.  Go to Setup > Custom Settings > Next to “Hierarchy Settings” click on “Manage” > Edit > Next to “Prevent Term Deletion” enable the checkbox > Save
2. Create a Contact, an Academic Program Account, a Course, a Course Offering, a Course Connection, a Term, and some Term Grades (all related to the Contact)
3. Attempt to Delete the Term.
--> Actual & Expected, cannot delete & receive an error message, "This record can't be deleted because it has one or more related records associated with it. Delete the associated records first, then delete this record. To determine which records should be deleted first, click the Related tab. If you don't see related records, or if you're unable to delete them, contact your System Administrator for assistance."
4. Delete the Term Grade.
--> Actual & Expected : Term Grade is Deleted.
5. Attempt to Delete the Term
--> Actual : Term is Deleted. Course Offerings associated with that Term are also Deleted. The Course Connection still exists but is no longer associated to a Course Offering.
--> Expected : cannot delete term and receive same error message as in step 3.

**Comment by dgamboni** [comment] 2019-12-30 21:54
**lurch: add

**Comment by LurchTheButler** [comment] 2019-12-30 21:55
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HqGIQA0" target="_blank">W-038393</a>

**Comment by robertbwatson** [comment] 2020-02-07 22:43
Closing this as it seems like it is now a duplicate of #1086 -- fyi @dgamboni

**Closed by robertbwatson** 2020-02-07 22:43 UTC
Labels: accepted, enhancement
