### ISSUE TITLE
[EDA] Add functionality to support MiddleName in Administrative Account Name Format

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#1256] opened 2020-07-23 14:34 UTC
Reported in the [Hub](https://powerofus.force.com/s/question/0D51E00005MGfZYSA1/using-middle-name-in-administrative-account-naming) on 7/14/2020

* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

A customer identified that they were unable to get {!MiddleName} to work when creating a custom administrative account naming convention (using the Other option) in EDA Settings. The same experience exists with Households. Upon further investigation, it was identified that UTIL_ACCT_Naming.cls does not include 'MiddleName'.

For example: {!{!FirstName}} {!MiddleName} {!LastName} Administrative Account

[Existing documentation](https://powerofus.force.com/s/article/EDA-Customize-Admin-and-HH-Acct-Names#ariaid-title7) states that: "For both Administrative Accounts and Household Accounts, you can include any standard Contact field in the custom name format. Custom fields aren't currently supported." That being said, Middle Name, just like Suffix (which has been coded), is a standard field.

* **What is the expected behavior?**

That {!MiddleName} is supported in the Administrative and Household Account Naming formats when OTHER is selected.

* **What is the motivation / use case for changing the behavior?**

EDA already supports the usage of Suffix in Administrative and Household Account Name formats when OTHER is selected and it's unclear why Middle Name would have been left out of the code.

Adding functionality to support MiddleName in Administrative Account Name Format will allow a customer to be able to differentiate the otherwise identical first and last names of contacts who are indeed different people, not to mention the support this gives a customer with deduplication efforts.

**Comment by jacebryan** [comment] 2020-07-23 14:38
**lurch: attach W-042709

**Comment by LurchTheButler** [comment] 2020-07-23 14:40
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hckqQAA" target="_blank">W-042709</a>

**Comment by MatthewBlanski** [comment] 2020-09-11 18:35
Duplicate of #573

**Closed** 2020-09-11 18:36 UTC
Labels: Customer Reported, duplicate

**Comment by jacebryan** [comment] 2020-11-16 23:07
We should expand this Issue to include all standard fields and not just Middle Name. For example: Selecting the Other Administrative Account Name Format option and entering {!AssistantName} gives the following error: hed.TDTM_Contact: execution of AfterInsert caused by: System.SObjectException: SObject row was retrieved via SOQL without querying the requested field: Contact.AssistantName (hed) I would recommend reopening this Issue as the Issue it was marked as a Duplicate of (#573 ) focuses on Custom fields and not standard fields.
