### ISSUE TITLE
Minor error loading HEDA Settings page quickly

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/EDA#421] opened 2017-05-09 21:02 UTC
![screen shot 2017-05-08 at 12 32 06 pm](https://cloud.githubusercontent.com/assets/204643/25872516/f2187e58-34bf-11e7-865b-6972619147a9.png)

Occasionally HEDA Settings pages will display this error when navigating quickly. It would be nice to prevent this from happening, because it sometimes interferes with automated browser tests and it looks scary to users.

**Comment by robertbwatson** [comment] 2019-05-23 23:58
I haven't ever seen this - we should see if this is still an issue and if it's not, we can probably close this @jacebryan

**Comment by jacebryan** [comment] 2019-05-24 12:54
@robertbwatson - Closing this issue now. I've not seen this issue and cannot reproduce it.

**Closed by jacebryan** 2019-05-24 12:54 UTC
Labels: bug, enhancement
